---
- name: install iptables-persistent
  environment:
       DEBIAN_FRONTEND: noninteractive
  apt:
    name="iptables-persistent"

- name: copy iptables config
  copy:
    src=rules.v4
    dest=/etc/iptables/rules.v4
    owner=root
    group=root
    mode=0644
  notify: reload iptable rules


