---
- name: install ntp deamon
  apt:
    name: ntp
    state: present
  register: ntp_installed

- name: install ntpdate
  apt:
    name: ntpdate
    state: present

- name: create ntp config
  copy:
    src=ntp.conf
    dest=/etc/ntp.conf
    mode=640
  when: ntp_installed|success
  notify:
    - restart ntp
